const CUSTOM_EVENT_STRINGS = {
  COMMAND_START: 'COMMAND_START',
  COMMAND_MENU: 'COMMAND_MENU',
  COMMAND_HELP: 'COMMAND_HELP',
  COMMAND_SETTINGS: 'COMMAND_SETTINGS',
  COMMAND_LIMIT: 'COMMAND_LIMIT',
  COMMAND_SUBSCRIBE: 'COMMAND_SUBSCRIBE',
  COMMAND_TRANSLATE: 'COMMAND_TRANSLATE',
  COMMAND_IMAGE_TRANSLATE: 'COMMAND_IMAGE_TRANSLATE',

  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
};

module.exports = { CUSTOM_EVENT_STRINGS };
